name: Bug report
description: Report a reproducible problem in codex-notify
title: "[Bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please include concrete reproduction steps.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Short description of the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Numbered steps
      placeholder: |
        1. Run ...
        2. Trigger ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: codex-notify version
      placeholder: "0.2.1"
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: macOS version
      placeholder: "macOS 15.x"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant output
      description: Paste `codex-notify doctor` or errors
      render: shell
