name: Feature request
description: Suggest an improvement or new capability
title: "[Feature] "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve?
      placeholder: Current behavior and limitation
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should be added or changed?
      placeholder: Concrete expected behavior
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Workarounds or other options
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Anything else useful (environment, screenshots, payload examples)
